### ISSUE TITLE
Allow for retries of scenario steps

### ISSUE THREAD

**Issue by sarudak** [mhjort/clj-gatling#22]
It would be nice to be able to specify scenario steps to be retried at the scenario level and keep track of the failures. The current method I'm using uses a retry inside the called function but it's not apparent in the result set that there was a failure and a retry happened it just looks like a really long request.

**Comment by mhjort** [comment]
Would you like to see retries somehow mentioned in a generated report? Because at the moment report format is limited to what gatling-highcharts component can produce.

However, it would be rather easy to implement the retry-count option for scenario step which will just retry failed request and increase the error (KO) count.

**Comment by sarudak** [comment]
Yeah I would like to see the failure but I would like the scenario to try the step a couple more times before giving up and starting over.

**Comment by mhjort** [comment]
Added this to Future milestone because it makes sense to do this after https://github.com/mhjort/clj-gatling/issues/26 is solved.

**Comment by mhjort** [comment]
It is possibly to retry actions by using dynamic scenarios and `step-fn`. Closing this one for now.
